import { CityData, PlaceItem, FoodItem } from "@/types";

export const CURATED_CITIES: Record<string, CityData> = {
  bangalore: {
    cityName: "Bangalore",
    state: "Karnataka",
    tagline: "Garden City & India's Tech and Craft Beer Capital",
    famousPlaces: [
      {
        id: "blr-palace",
        name: "Bangalore Palace",
        category: "Heritage",
        estimatedCost: 450,
        durationHours: 2.5,
        rating: 4.5,
        description: "Tudor-style royal palace featuring ornate wooden carvings and lush gardens.",
        isFamous: true,
        area: "Vasanth Nagar",
      },
      {
        id: "blr-lalbagh",
        name: "Lalbagh Botanical Garden",
        category: "Nature",
        estimatedCost: 30,
        durationHours: 2,
        rating: 4.6,
        description: "Historic 240-acre botanical garden with a glasshouse inspired by London's Crystal Palace.",
        isFamous: true,
        area: "South Bangalore",
      },
      {
        id: "blr-cubbon",
        name: "Cubbon Park & Vidhana Soudha",
        category: "Nature",
        estimatedCost: 0,
        durationHours: 2,
        rating: 4.7,
        description: "Sprawling green lung of the city surrounded by neo-Dravidian state architecture.",
        isFamous: true,
        area: "Central Bangalore",
      },
      {
        id: "blr-nandi",
        name: "Nandi Hills Sunrise Point",
        category: "Viewpoint",
        estimatedCost: 150,
        durationHours: 4,
        rating: 4.8,
        description: "Ancient hill fortress famous for misty sunrise views, 60km outside the city core.",
        isFamous: true,
        area: "Chikkaballapur",
      },
      {
        id: "blr-commercial",
        name: "Commercial Street & MG Road",
        category: "Shopping",
        estimatedCost: 0,
        durationHours: 3,
        rating: 4.4,
        description: "Vibrant shopping street lined with local textiles, handicrafts, and street vendors.",
        isFamous: true,
        area: "Central Bangalore",
      },
      {
        id: "blr-iskcon",
        name: "ISKCON Sri Radha Krishna Temple",
        category: "Culture",
        estimatedCost: 0,
        durationHours: 1.5,
        rating: 4.7,
        description: "Monumental modern cultural and spiritual campus perched on Hare Krishna Hill.",
        isFamous: true,
        area: "Rajajinagar",
      },
    ],
    famousFoods: [
      {
        id: "blr-dosa",
        name: "Crispy Masala Dosa with Chutney",
        estimatedCost: 80,
        mealType: "Breakfast",
        isFamous: true,
        description: "Golden ghee-roasted crêpe stuffed with spiced potato mash, served at legendary darshinis.",
      },
      {
        id: "blr-coffee",
        name: "Traditional South Indian Filter Coffee",
        estimatedCost: 40,
        mealType: "Snack / Drink",
        isFamous: true,
        description: "Freshly brewed chicory blend frothed into stainless steel dabarah and tumbler.",
      },
      {
        id: "blr-thali",
        name: "Authentic Karnataka Banana Leaf Thali",
        estimatedCost: 220,
        mealType: "Lunch",
        isFamous: true,
        description: "Unlimited regional feast of sambar, rasam, saaru, palya, payasa, and crisp papad.",
      },
      {
        id: "blr-bisibelebath",
        name: "Bisi Bele Bath with Boondi",
        estimatedCost: 90,
        mealType: "Lunch",
        isFamous: true,
        description: "Rich, hot lentil-rice dish infused with cinnamon, cloves, nutmeg, and crunchy boondi.",
      },
      {
        id: "blr-brewery",
        name: "Craft Beer & Pub Bites",
        estimatedCost: 450,
        mealType: "Dinner",
        isFamous: true,
        description: "Indiranagar / Koramangala microbrewery tasting with fresh wheat beers and bar snacks.",
      },
    ],
    localExperiences: [
      "Early morning stroll & coconut water at Cubbon Park",
      "Breakfast hop across VV Puram Food Street",
      "Café hopping along 100 Feet Road, Indiranagar",
      "Second-hand book browsing on Church Street",
    ],
  },
  goa: {
    cityName: "Goa",
    state: "Goa",
    tagline: "Sun, Sand, Portuguese Heritage & Coastal Vibes",
    famousPlaces: [
      {
        id: "goa-aguada",
        name: "Fort Aguada & Lighthouse",
        category: "Heritage",
        estimatedCost: 50,
        durationHours: 2,
        rating: 4.5,
        description: "17th-century Portuguese fortress overlooking the vast Arabian Sea.",
        isFamous: true,
        area: "Sinquerim",
      },
      {
        id: "goa-anjuna",
        name: "Anjuna & Vagator Cliff Beach",
        category: "Nature",
        estimatedCost: 0,
        durationHours: 3,
        rating: 4.6,
        description: "Red-rock cliffs, sandy shores, vibrant shacks, and dramatic sunset viewpoints.",
        isFamous: true,
        area: "North Goa",
      },
      {
        id: "goa-fontainhas",
        name: "Fontainhas Latin Quarter",
        category: "Culture",
        estimatedCost: 0,
        durationHours: 2,
        rating: 4.7,
        description: "Charming historic neighborhood with pastel-painted Portuguese villas and art cafes.",
        isFamous: true,
        area: "Panaji",
      },
      {
        id: "goa-dudhsagar",
        name: "Dudhsagar Waterfalls Trek",
        category: "Nature",
        estimatedCost: 600,
        durationHours: 5,
        rating: 4.7,
        description: "Four-tiered majestic waterfall cascading like a sea of milk through Western Ghats.",
        isFamous: true,
        area: "Sanguem",
      },
    ],
    famousFoods: [
      {
        id: "goa-fishcurry",
        name: "Goan Fish Curry Rice Thali",
        estimatedCost: 250,
        mealType: "Lunch",
        isFamous: true,
        description: "Tangy coconut-kokum curry with kingfish, kismoor, and steamed red rice.",
      },
      {
        id: "goa-poi",
        name: "Pao / Poi with Goan Chorizo / Ros Omelette",
        estimatedCost: 120,
        mealType: "Breakfast",
        isFamous: true,
        description: "Crusty wood-fired Goan bread stuffed with spicy street fillings.",
      },
      {
        id: "goa-bebinca",
        name: "Bebinca Multi-Layered Dessert",
        estimatedCost: 140,
        mealType: "Snack / Drink",
        isFamous: true,
        description: "Traditional 7-layer baked coconut milk, ghee, and egg yolk delicacy.",
      },
    ],
    localExperiences: [
      "Rent a scooter to cruise the scenic coconut groves of Siolim",
      "Sunset shack listening to live indie music",
      "Spice plantation walk and traditional Goan buffet",
    ],
  },
  mumbai: {
    cityName: "Mumbai",
    state: "Maharashtra",
    tagline: "City of Dreams, Marine Drive & Street Food Culture",
    famousPlaces: [
      {
        id: "mum-gateway",
        name: "Gateway of India & Taj Palace",
        category: "Heritage",
        estimatedCost: 0,
        durationHours: 1.5,
        rating: 4.7,
        description: "Iconic Indo-Saracenic triumphal arch monument built overlooking Mumbai Harbor.",
        isFamous: true,
        area: "Colaba",
      },
      {
        id: "mum-marinedrive",
        name: "Marine Drive (Queen's Necklace)",
        category: "Viewpoint",
        estimatedCost: 0,
        durationHours: 2,
        rating: 4.8,
        description: "3.6-kilometer seaside promenade offering breezy sea panoramas and twinkling night lights.",
        isFamous: true,
        area: "South Mumbai",
      },
      {
        id: "mum-elephanta",
        name: "Elephanta Caves (Ferry + Entry)",
        category: "Culture",
        estimatedCost: 350,
        durationHours: 4,
        rating: 4.5,
        description: "UNESCO World Heritage rock-cut cave temples dedicated to Lord Shiva on Elephanta Island.",
        isFamous: true,
        area: "Harbor",
      },
    ],
    famousFoods: [
      {
        id: "mum-vadapav",
        name: "Mumbai Vada Pav with Lasun Chutney",
        estimatedCost: 30,
        mealType: "Snack / Drink",
        isFamous: true,
        description: "Spicy batata vada tucked inside warm pav with fiery dry garlic chutney.",
      },
      {
        id: "mum-pavbhaji",
        name: "Sardar Butter Pav Bhaji",
        estimatedCost: 180,
        mealType: "Dinner",
        isFamous: true,
        description: "Sizzling buttery mashed vegetable curry served with toasted ladi pav.",
      },
      {
        id: "mum-bunmaska",
        name: "Irani Bun Maska & Chai",
        estimatedCost: 60,
        mealType: "Breakfast",
        isFamous: true,
        description: "Warm soft bun slathered with salted butter dunked into rich Irani chai.",
      },
    ],
    localExperiences: [
      "Late-night drive down the Bandra-Worli Sea Link",
      "Chaat tasting at Girgaon Chowpatty beach during sunset",
      "Heritage walking tour through Fort and Kala Ghoda",
    ],
  },
  delhi: {
    cityName: "Delhi",
    state: "Delhi NCR",
    tagline: "Imperial Monuments, Mughal Flavors & Vibrant Bazaars",
    famousPlaces: [
      {
        id: "del-redfort",
        name: "Red Fort (Lal Qila)",
        category: "Heritage",
        estimatedCost: 50,
        durationHours: 2.5,
        rating: 4.6,
        description: "Massive 17th-century red sandstone fortress that served as the main residence of Mughal emperors.",
        isFamous: true,
        area: "Old Delhi",
      },
      {
        id: "del-qutub",
        name: "Qutub Minar & Mehrauli Complex",
        category: "Heritage",
        estimatedCost: 40,
        durationHours: 2,
        rating: 4.7,
        description: "Tallest brick minaret in the world surrounded by ancient ruins and the Iron Pillar.",
        isFamous: true,
        area: "South Delhi",
      },
      {
        id: "del-indiagate",
        name: "India Gate & Kartavya Path",
        category: "Heritage",
        estimatedCost: 0,
        durationHours: 1.5,
        rating: 4.6,
        description: "Solemn war memorial arch honoring Indian soldiers, glowing spectacularly after dusk.",
        isFamous: true,
        area: "Central Delhi",
      },
    ],
    famousFoods: [
      {
        id: "del-cholebhature",
        name: "Crispy Chole Bhature with Pickled Carrots",
        estimatedCost: 120,
        mealType: "Breakfast",
        isFamous: true,
        description: "Puffed deep-fried bread paired with spicy chickpea gravy and sweet lassi.",
      },
      {
        id: "del-paranthe",
        name: "Stuffed Paranthe at Paranthe Wali Gali",
        estimatedCost: 150,
        mealType: "Lunch",
        isFamous: true,
        description: "Shallow-fried flatbreads stuffed with paneer, potato, or dry fruits in Chandni Chowk.",
      },
      {
        id: "del-chaat",
        name: "Old Delhi Dahi Bhalla & Golgappe",
        estimatedCost: 70,
        mealType: "Snack / Drink",
        isFamous: true,
        description: "Crispy puris bursting with tangy tamarind water and spiced potato-sprout filling.",
      },
    ],
    localExperiences: [
      "Rickshaw safari through the aromatic spice lanes of Khari Baoli",
      "Evening qawwali music recital at Hazrat Nizamuddin Dargah",
      "Strolling the serene Mughal gardens of Humayun's Tomb",
    ],
  },
  jaipur: {
    cityName: "Jaipur",
    state: "Rajasthan",
    tagline: "The Pink City: Royal Forts, Haveli Bazaars & Grandeur",
    famousPlaces: [
      {
        id: "jai-amber",
        name: "Amber Fort & Sheesh Mahal",
        category: "Heritage",
        estimatedCost: 100,
        durationHours: 3.5,
        rating: 4.8,
        description: "Majestic hilltop fort known for its intricate mirror palace and panoramic lake views.",
        isFamous: true,
        area: "Amer",
      },
      {
        id: "jai-hawa",
        name: "Hawa Mahal (Palace of Winds)",
        category: "Heritage",
        estimatedCost: 50,
        durationHours: 1.5,
        rating: 4.5,
        description: "Five-story pink sandstone palace with 953 honeycomb windows designed for royal breezes.",
        isFamous: true,
        area: "Badi Choupad",
      },
      {
        id: "jai-nahargarh",
        name: "Nahargarh Fort Sunset View",
        category: "Viewpoint",
        estimatedCost: 50,
        durationHours: 2.5,
        rating: 4.7,
        description: "Historic ramparts sitting atop the Aravalli hills looking over the entire pink city.",
        isFamous: true,
        area: "Aravalli Range",
      },
    ],
    famousFoods: [
      {
        id: "jai-dalbaati",
        name: "Royal Dal Baati Churma Thali",
        estimatedCost: 280,
        mealType: "Lunch",
        isFamous: true,
        description: "Hard wheat balls baked in ghee, served with panchmel dal, gatte, and sweet churma.",
      },
      {
        id: "jai-pyazkachori",
        name: "Rawat Pyaz Kachori & Mirchi Vada",
        estimatedCost: 50,
        mealType: "Breakfast",
        isFamous: true,
        description: "Flaky deep-fried pastry stuffed with spiced caramelized onions, served piping hot.",
      },
      {
        id: "jai-lassi",
        name: "Kulhad Makhan Lassi on MI Road",
        estimatedCost: 60,
        mealType: "Snack / Drink",
        isFamous: true,
        description: "Thick creamy yogurt churned in earthen clay cups topped with a generous dollop of malai.",
      },
    ],
    localExperiences: [
      "Sunset chai overlooking the glowing facade of Hawa Mahal",
      "Block-print textile shopping in Johari and Bapu Bazaars",
      "Stargazing at the massive stone astronomical instruments of Jantar Mantar",
    ],
  },
  manali: {
    cityName: "Manali",
    state: "Himachal Pradesh",
    tagline: "Snowy Pine Valleys, Mountain Passes & Adventure",
    famousPlaces: [
      {
        id: "man-solang",
        name: "Solang Valley Adventure Arena",
        category: "Entertainment",
        estimatedCost: 500,
        durationHours: 4,
        rating: 4.6,
        description: "High-altitude valley famous for paragliding, zorbing, quad biking, and winter skiing.",
        isFamous: true,
        area: "Solang",
      },
      {
        id: "man-atal",
        name: "Atal Tunnel & Sissu Waterfall",
        category: "Nature",
        estimatedCost: 200,
        durationHours: 4,
        rating: 4.8,
        description: "Engineering marvel cutting through the Pir Panjal range into the rugged Lahaul valley.",
        isFamous: true,
        area: "Lahaul Border",
      },
      {
        id: "man-hadimba",
        name: "Hadimba Devi Cedar Temple",
        category: "Culture",
        estimatedCost: 20,
        durationHours: 1.5,
        rating: 4.5,
        description: "Historic pagoda-style wooden temple built in 1553 amidst tall deodar forests.",
        isFamous: true,
        area: "Dhungri",
      },
    ],
    famousFoods: [
      {
        id: "man-siddu",
        name: "Himachali Siddu with Ghee & Dal",
        estimatedCost: 100,
        mealType: "Breakfast",
        isFamous: true,
        description: "Steamed fermented wheat bun filled with walnut, poppy seed, or spiced lentil paste.",
      },
      {
        id: "man-trout",
        name: "Wood-Fired Himalayan Rainbow Trout",
        estimatedCost: 450,
        mealType: "Dinner",
        isFamous: true,
        description: "Fresh river trout sautéed in lemon butter herbs, a signature mountain delicacy.",
      },
      {
        id: "man-thukpa",
        name: "Hot Tibetan Thukpa & Steamed Momos",
        estimatedCost: 120,
        mealType: "Lunch",
        isFamous: true,
        description: "Comforting piping-hot noodle broth packed with mountain herbs and vegetables.",
      },
    ],
    localExperiences: [
      "Strolling through Old Manali's bohemian cafes and acoustic music sessions",
      "Dip in the natural hot sulphur springs of Vashisht village",
      "Scenic riverside walk alongside the roaring Beas river",
    ],
  },
  kerala: {
    cityName: "Kerala (Munnar & Alleppey)",
    state: "Kerala",
    tagline: "God's Own Country: Emerald Backwaters & Rolling Tea Hills",
    famousPlaces: [
      {
        id: "ker-backwaters",
        name: "Alleppey Backwaters Shikhara / Houseboat",
        category: "Nature",
        estimatedCost: 800,
        durationHours: 4,
        rating: 4.8,
        description: "Glide through tranquil palm-fringed canals, paddy fields, and serene lagoons.",
        isFamous: true,
        area: "Alleppey",
      },
      {
        id: "ker-teagardens",
        name: "Munnar Tea Plantations & Kolukkumalai",
        category: "Viewpoint",
        estimatedCost: 150,
        durationHours: 3,
        rating: 4.7,
        description: "World's highest tea estates carpeted in mist with panoramic sunrise peaks.",
        isFamous: true,
        area: "Munnar",
      },
      {
        id: "ker-kathakali",
        name: "Kalaripayattu & Kathakali Cultural Show",
        category: "Culture",
        estimatedCost: 350,
        durationHours: 2,
        rating: 4.6,
        description: "Ancient Indian martial art demonstrations and classical Kerala dance-drama.",
        isFamous: true,
        area: "Thekkady / Kochi",
      },
    ],
    famousFoods: [
      {
        id: "ker-appam",
        name: "Fluffy Appam with Vegetable / Chicken Stew",
        estimatedCost: 130,
        mealType: "Breakfast",
        isFamous: true,
        description: "Fermented rice pancake with soft pillowy center and crisp lace borders in coconut milk.",
      },
      {
        id: "ker-sadya",
        name: "Traditional Kerala Sadya on Plantain Leaf",
        estimatedCost: 260,
        mealType: "Lunch",
        isFamous: true,
        description: "Grand vegetarian banquet with 20+ authentic dishes including avial, olan, and payasam.",
      },
      {
        id: "ker-fishpolli",
        name: "Karimeen Pollichathu (Pearl Spot Fish)",
        estimatedCost: 380,
        mealType: "Dinner",
        isFamous: true,
        description: "Spiced pearl spot fish wrapped inside scorched banana leaf and pan-roasted to perfection.",
      },
    ],
    localExperiences: [
      "Kayaking down village canals at dawn to spot kingfishers",
      "Ayurvedic herbal massage and wellness therapy",
      "Spice garden walk tasting fresh cardamom, cloves, and vanilla",
    ],
  },
};

/**
 * Retrieves curated destination data or generates a realistic, sensible profile
 * for any custom city entered by the user.
 */
export function getCityData(destinationName: string): CityData {
  const cleanName = (destinationName || "").toLowerCase().trim();

  // 1. Check exact or partial matches
  for (const [key, data] of Object.entries(CURATED_CITIES)) {
    if (cleanName.includes(key) || key.includes(cleanName)) {
      return data;
    }
  }

  // 2. Procedural generator for any entered custom city (e.g. Udaipur, Ooty, Pondicherry, Paris, Dubai)
  const capitalized = destinationName ? destinationName.charAt(0).toUpperCase() + destinationName.slice(1) : "Destination";

  return {
    cityName: capitalized,
    state: "Explore India & Beyond",
    tagline: `Discover the top sights, local flavors, and hidden gems of ${capitalized}`,
    famousPlaces: [
      {
        id: `custom-${cleanName}-1`,
        name: `${capitalized} Heritage & Old Town Quarter`,
        category: "Heritage",
        estimatedCost: 150,
        durationHours: 2.5,
        rating: 4.6,
        description: `Explore the historical monuments, town squares, and iconic architecture of ${capitalized}.`,
        isFamous: true,
        area: "Central",
      },
      {
        id: `custom-${cleanName}-2`,
        name: `${capitalized} Nature Park & Scenic Lake Promenade`,
        category: "Nature",
        estimatedCost: 50,
        durationHours: 2,
        rating: 4.5,
        description: `Relaxing scenic nature area popular with locals for sunrise strolls and photography.`,
        isFamous: true,
        area: "North",
      },
      {
        id: `custom-${cleanName}-3`,
        name: `Local Handicrafts Bazaar & Main Market`,
        category: "Shopping",
        estimatedCost: 0,
        durationHours: 2.5,
        rating: 4.4,
        description: `Vibrant street market famous for regional souvenirs, handcrafted textiles, and street snacks.`,
        isFamous: true,
        area: "Market Square",
      },
      {
        id: `custom-${cleanName}-4`,
        name: `${capitalized} Hilltop Viewpoint & Sunset Pavilion`,
        category: "Viewpoint",
        estimatedCost: 100,
        durationHours: 2,
        rating: 4.7,
        description: `Panoramic observation point overlooking the city skyline and mountain horizons.`,
        isFamous: true,
        area: "High Ridge",
      },
    ],
    famousFoods: [
      {
        id: `custom-food-${cleanName}-1`,
        name: `${capitalized} Signature Breakfast Special`,
        estimatedCost: 90,
        mealType: "Breakfast",
        isFamous: true,
        description: `Traditional breakfast favorite made fresh by beloved local vendors.`,
      },
      {
        id: `custom-food-${cleanName}-2`,
        name: `Regional Thali & Specialty Lunch`,
        estimatedCost: 200,
        mealType: "Lunch",
        isFamous: true,
        description: `Multi-dish traditional platter representing the authentic culinary heritage of the region.`,
      },
      {
        id: `custom-food-${cleanName}-3`,
        name: `Popular Evening Street Bites & Chai`,
        estimatedCost: 70,
        mealType: "Snack / Drink",
        isFamous: true,
        description: `Crispy savory street snacks paired with hot masala tea at bustling local stalls.`,
      },
      {
        id: `custom-food-${cleanName}-4`,
        name: `Local Specialty Dinner Feast`,
        estimatedCost: 350,
        mealType: "Dinner",
        isFamous: true,
        description: `Chef special dinner at a celebrated local restaurant highlighting authentic seasonal ingredients.`,
      },
    ],
    localExperiences: [
      `Morning walking tour through the heritage heart of ${capitalized}`,
      `Sampling street food specialties at the bustling evening market`,
      `Sunset photography from the most scenic vantage point`,
      `Visiting an artisanal craft workshop to see traditional artisans at work`,
    ],
  };
}
