export interface CustomerCohortItem {
  id: string;
  name: string;
  email: string;
  clientType: 'Student Group' | 'Solo Backpacker' | 'Weekend Couple' | 'Family Vacationer' | 'Corporate Professional';
  origin: string;
  destination: string;
  durationDays: number;
  travelers: number;
  plannedBudget: number;
  actualSpend: number;
  conversionStage: 'Payment Completed (Premium)' | 'Expense Tracking Active' | 'Budget Optimized' | 'Trip Planned';
  feedbackRating: number; // out of 5
  clientCollaborationNote: string;
  joinedDate: string;
}

export const EVALUATION_CUSTOMERS: CustomerCohortItem[] = [
  {
    id: "cust-01",
    name: "Aarav Sharma",
    email: "aarav.sharma@pes.edu",
    clientType: "Student Group",
    origin: "Bangalore",
    destination: "Goa",
    durationDays: 4,
    travelers: 4,
    plannedBudget: 32000,
    actualSpend: 30450,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.8,
    clientCollaborationNote: "Requested group auto vs cab comparison. Found that 1 cab was ₹600 cheaper than 2 autos per day.",
    joinedDate: "2026-09-02",
  },
  {
    id: "cust-02",
    name: "Pooja Hegde",
    email: "pooja.hegde@rvce.edu.in",
    clientType: "Solo Backpacker",
    origin: "Mysore",
    destination: "Manali",
    durationDays: 5,
    travelers: 1,
    plannedBudget: 18000,
    actualSpend: 16800,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.9,
    clientCollaborationNote: "Suggested women safety night advisory. Loved the 1091/112 emergency helpline integration.",
    joinedDate: "2026-09-03",
  },
  {
    id: "cust-03",
    name: "Vikram & Sneha Sen",
    email: "vikram.sen@wipro.com",
    clientType: "Weekend Couple",
    origin: "Bangalore",
    destination: "Ooty",
    durationDays: 3,
    travelers: 2,
    plannedBudget: 22000,
    actualSpend: 21500,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.7,
    clientCollaborationNote: "Tested Couple Package engine. Stated that pre-budgeting candlelit dinner and heritage toy train saved ₹2,000.",
    joinedDate: "2026-09-04",
  },
  {
    id: "cust-04",
    name: "Rohan Kulkarni",
    email: "rohan.k@msrit.edu",
    clientType: "Student Group",
    origin: "Hubli",
    destination: "Gokarna",
    durationDays: 3,
    travelers: 5,
    plannedBudget: 25000,
    actualSpend: 23900,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.6,
    clientCollaborationNote: "Shared ledger feedback: Needed real-time food and fuel split logging for college road trips.",
    joinedDate: "2026-09-05",
  },
  {
    id: "cust-05",
    name: "Rajesh & Priya Iyer",
    email: "rajesh.iyer@infosys.com",
    clientType: "Family Vacationer",
    origin: "Chennai",
    destination: "Munnar",
    durationDays: 4,
    travelers: 4,
    plannedBudget: 45000,
    actualSpend: 43200,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 5.0,
    clientCollaborationNote: "Highlighted the Hidden Cost Detector. Avoided ₹2,400 unexpected resort taxes and hill-driver overnight fees.",
    joinedDate: "2026-09-06",
  },
  {
    id: "cust-06",
    name: "Tanvi Deshmukh",
    email: "tanvi.d@bmsce.ac.in",
    clientType: "Solo Backpacker",
    origin: "Pune",
    destination: "Jaipur",
    durationDays: 4,
    travelers: 1,
    plannedBudget: 14000,
    actualSpend: 13100,
    conversionStage: "Budget Optimized",
    feedbackRating: 4.8,
    clientCollaborationNote: "Used 'What-If' optimizer to switch from private city tour to composite heritage composite ticket, saving ₹1,200.",
    joinedDate: "2026-09-07",
  },
  {
    id: "cust-07",
    name: "Karthik Raja & Team",
    email: "karthik.r@vit.ac.in",
    clientType: "Student Group",
    origin: "Vellore",
    destination: "Pondicherry",
    durationDays: 3,
    travelers: 6,
    plannedBudget: 28000,
    actualSpend: 29100,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.5,
    clientCollaborationNote: "App alerted when café bill crossed 85% of food allocation. Prevented overspending on Day 2.",
    joinedDate: "2026-09-07",
  },
  {
    id: "cust-08",
    name: "Nikhil Joshi",
    email: "nikhil.j@deloitte.com",
    clientType: "Corporate Professional",
    origin: "Hyderabad",
    destination: "Bangalore",
    durationDays: 3,
    travelers: 1,
    plannedBudget: 19000,
    actualSpend: 17800,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.9,
    clientCollaborationNote: "Evaluated Smart Transport comparison: Chose Vande Bharat AC Chair car instead of Flight, saving ₹3,100 after airport taxi math.",
    joinedDate: "2026-09-08",
  },
  {
    id: "cust-09",
    name: "Ananya Mukherjee",
    email: "ananya.m@jadavpur.edu",
    clientType: "Solo Backpacker",
    origin: "Kolkata",
    destination: "Darjeeling",
    durationDays: 4,
    travelers: 1,
    plannedBudget: 15000,
    actualSpend: 14200,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.7,
    clientCollaborationNote: "Tested famous food adder: Glenary's bakery breakfast and local momo trails added directly into meal budget.",
    joinedDate: "2026-09-09",
  },
  {
    id: "cust-10",
    name: "Sameer & Divya Reddy",
    email: "sameer.r@tcs.com",
    clientType: "Weekend Couple",
    origin: "Hyderabad",
    destination: "Coorg",
    durationDays: 3,
    travelers: 2,
    plannedBudget: 26000,
    actualSpend: 24900,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.8,
    clientCollaborationNote: "Requested homestay vs resort comparison. Saved ₹4,200 while enjoying authentic Kodava plantation breakfast.",
    joinedDate: "2026-09-09",
  },
  {
    id: "cust-11",
    name: "Aditya Verma",
    email: "aditya.v@iitb.ac.in",
    clientType: "Student Group",
    origin: "Mumbai",
    destination: "Lonavala",
    durationDays: 2,
    travelers: 4,
    plannedBudget: 16000,
    actualSpend: 15400,
    conversionStage: "Trip Planned",
    feedbackRating: 4.6,
    clientCollaborationNote: "Noted highway expressway toll estimate (₹320) was accurately caught by Hidden Cost audit.",
    joinedDate: "2026-09-10",
  },
  {
    id: "cust-12",
    name: "Meera Nambiar",
    email: "meera.n@kerala.gov.in",
    clientType: "Family Vacationer",
    origin: "Kochi",
    destination: "Wayanad",
    durationDays: 4,
    travelers: 5,
    plannedBudget: 38000,
    actualSpend: 36500,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.9,
    clientCollaborationNote: "Appreciated the clear breakdown between vehicle fuel vs national park entry permits.",
    joinedDate: "2026-09-11",
  },
  {
    id: "cust-13",
    name: "Harish & Team (6 Mech Students)",
    email: "harish.mech@nitk.edu.in",
    clientType: "Student Group",
    origin: "Mangalore",
    destination: "Dandeli",
    durationDays: 3,
    travelers: 6,
    plannedBudget: 30000,
    actualSpend: 28800,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.8,
    clientCollaborationNote: "River rafting activity price benchmark matched actual booking operator on ground.",
    joinedDate: "2026-09-11",
  },
  {
    id: "cust-14",
    name: "Shruti Bansal",
    email: "shruti.b@du.ac.in",
    clientType: "Solo Backpacker",
    origin: "Delhi",
    destination: "Rishikesh",
    durationDays: 3,
    travelers: 1,
    plannedBudget: 11000,
    actualSpend: 10400,
    conversionStage: "Budget Optimized",
    feedbackRating: 4.7,
    clientCollaborationNote: "Subscribed to ₹1 trial. The AI trade-off solver replaced high taxi fare with shared e-rickshaw route.",
    joinedDate: "2026-09-12",
  },
  {
    id: "cust-15",
    name: "Pranav & Ritu Kapoor",
    email: "pranav.k@flipkart.com",
    clientType: "Weekend Couple",
    origin: "Gurgaon",
    destination: "Udaipur",
    durationDays: 3,
    travelers: 2,
    plannedBudget: 35000,
    actualSpend: 33900,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 5.0,
    clientCollaborationNote: "Praised Lake Pichola boat ride and City Palace combo ticketing recommendation.",
    joinedDate: "2026-09-12",
  },
  {
    id: "cust-16",
    name: "Gaurav Malhotra",
    email: "gaurav.m@accenture.com",
    clientType: "Corporate Professional",
    origin: "Mumbai",
    destination: "Goa",
    durationDays: 3,
    travelers: 2,
    plannedBudget: 28000,
    actualSpend: 27100,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.7,
    clientCollaborationNote: "Late-night MOPA airport transit alert suggested pre-booking KSRTC electric bus over ₹2,200 midnight taxi.",
    joinedDate: "2026-09-13",
  },
  {
    id: "cust-17",
    name: "Dr. Arvind Swaminathan",
    email: "arvind.s@apollo.org",
    clientType: "Family Vacationer",
    origin: "Bangalore",
    destination: "Kodaikanal",
    durationDays: 4,
    travelers: 4,
    plannedBudget: 42000,
    actualSpend: 40800,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.9,
    clientCollaborationNote: "Accurate room occupancy math (2 rooms for 4 travelers) avoided extra bed surcharges at check-in.",
    joinedDate: "2026-09-13",
  },
  {
    id: "cust-18",
    name: "Siddharth Jain",
    email: "sid.jain@bits-pilani.ac.in",
    clientType: "Student Group",
    origin: "Jaipur",
    destination: "Jaisalmer",
    durationDays: 3,
    travelers: 4,
    plannedBudget: 24000,
    actualSpend: 23100,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.8,
    clientCollaborationNote: "Desert safari package transparency ensured dune bashing and folk dance weren't charged separately.",
    joinedDate: "2026-09-14",
  },
  {
    id: "cust-19",
    name: "Aishwarya Pillai",
    email: "aishwarya.p@cet.ac.in",
    clientType: "Solo Backpacker",
    origin: "Trivandrum",
    destination: "Hampi",
    durationDays: 4,
    travelers: 1,
    plannedBudget: 12500,
    actualSpend: 11900,
    conversionStage: "Budget Optimized",
    feedbackRating: 4.9,
    clientCollaborationNote: "Bicycle rental cost tracking and Virupaksha Temple guide pricing were spot on.",
    joinedDate: "2026-09-14",
  },
  {
    id: "cust-20",
    name: "Mohit & Neha Singhania",
    email: "mohit.s@zomato.com",
    clientType: "Weekend Couple",
    origin: "Delhi",
    destination: "Agra",
    durationDays: 2,
    travelers: 2,
    plannedBudget: 15000,
    actualSpend: 14200,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.6,
    clientCollaborationNote: "Gatimaan Express vs Yamuna Expressway toll+fuel comparison favored train by ₹800.",
    joinedDate: "2026-09-15",
  },
  {
    id: "cust-21",
    name: "Deepak & College Squad",
    email: "deepak.squad@mit.edu.in",
    clientType: "Student Group",
    origin: "Pune",
    destination: "Mahabaleshwar",
    durationDays: 3,
    travelers: 5,
    plannedBudget: 22000,
    actualSpend: 21100,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.7,
    clientCollaborationNote: "Mapro garden strawberry tasting and viewpoint entry tickets pre-calculated without surprises.",
    joinedDate: "2026-09-16",
  },
  {
    id: "cust-22",
    name: "Kavita Rao",
    email: "kavita.rao@osmania.ac.in",
    clientType: "Solo Backpacker",
    origin: "Hyderabad",
    destination: "Pondicherry",
    durationDays: 3,
    travelers: 1,
    plannedBudget: 13000,
    actualSpend: 12200,
    conversionStage: "Trip Planned",
    feedbackRating: 4.8,
    clientCollaborationNote: "Auroville Matrimandir free pass procedure clearly explained in activity advice.",
    joinedDate: "2026-09-16",
  },
  {
    id: "cust-23",
    name: "Suresh & Malini Chawla",
    email: "suresh.c@bhel.in",
    clientType: "Family Vacationer",
    origin: "Bhopal",
    destination: "Pachmarhi",
    durationDays: 3,
    travelers: 4,
    plannedBudget: 28000,
    actualSpend: 26900,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.7,
    clientCollaborationNote: "Forest department gypsy permit rates included beforehand in miscellaneous contingency.",
    joinedDate: "2026-09-17",
  },
  {
    id: "cust-24",
    name: "Vishal Patil",
    email: "vishal.patil@coep.ac.in",
    clientType: "Student Group",
    origin: "Pune",
    destination: "Goa",
    durationDays: 4,
    travelers: 4,
    plannedBudget: 29000,
    actualSpend: 27800,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.8,
    clientCollaborationNote: "KSRTC sleeper bus vs train waitlist comparison helped group lock confirmed bus seats early.",
    joinedDate: "2026-09-17",
  },
  {
    id: "cust-25",
    name: "Preeti Sundaram",
    email: "preeti.s@amazon.com",
    clientType: "Corporate Professional",
    origin: "Chennai",
    destination: "Bangalore",
    durationDays: 2,
    travelers: 1,
    plannedBudget: 14000,
    actualSpend: 13400,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 5.0,
    clientCollaborationNote: "Praised Bangalore Airport KIA electric AC bus recommendation (₹250 vs ₹1,200 cab).",
    joinedDate: "2026-09-18",
  },
  {
    id: "cust-26",
    name: "Tushar & Alok (Dorm Mates)",
    email: "tushar.a@thapar.edu",
    clientType: "Student Group",
    origin: "Chandigarh",
    destination: "Kasol",
    durationDays: 4,
    travelers: 3,
    plannedBudget: 19000,
    actualSpend: 18100,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.6,
    clientCollaborationNote: "Café food budgeting helped avoid cash shortages in remote Parvati Valley spots.",
    joinedDate: "2026-09-18",
  },
  {
    id: "cust-27",
    name: "Geetha Ramanathan",
    email: "geetha.r@madrasuniv.ac.in",
    clientType: "Solo Backpacker",
    origin: "Madurai",
    destination: "Tiruvannamalai",
    durationDays: 2,
    travelers: 1,
    plannedBudget: 7500,
    actualSpend: 6900,
    conversionStage: "Budget Optimized",
    feedbackRating: 4.9,
    clientCollaborationNote: "Girivalam walking route transit advice and ashram accommodation tariff accuracy appreciated.",
    joinedDate: "2026-09-19",
  },
  {
    id: "cust-28",
    name: "Varun & Meghna D'Souza",
    email: "varun.dsouza@swiggy.in",
    clientType: "Weekend Couple",
    origin: "Bangalore",
    destination: "Chikmagalur",
    durationDays: 3,
    travelers: 2,
    plannedBudget: 24000,
    actualSpend: 22800,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.8,
    clientCollaborationNote: "Mullayanagiri jeep transfer tariff was pre-budgeted accurately, avoiding spot negotiation.",
    joinedDate: "2026-09-19",
  },
  {
    id: "cust-29",
    name: "Anand Gupta & Family",
    email: "anand.g@tata.com",
    clientType: "Family Vacationer",
    origin: "Lucknow",
    destination: "Nainital",
    durationDays: 4,
    travelers: 5,
    plannedBudget: 46000,
    actualSpend: 44300,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.7,
    clientCollaborationNote: "Mall Road vehicle entry pass and ropeway ticket estimates saved time at counter queues.",
    joinedDate: "2026-09-20",
  },
  {
    id: "cust-30",
    name: "Bhavana Kulkarni",
    email: "bhavana.k@kle.ac.in",
    clientType: "Student Group",
    origin: "Belgaum",
    destination: "Goa",
    durationDays: 3,
    travelers: 4,
    plannedBudget: 21000,
    actualSpend: 19800,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.9,
    clientCollaborationNote: "Rented 2 two-wheelers instead of taxis based on local transit engine advice, saving ₹3,200.",
    joinedDate: "2026-09-20",
  },
  {
    id: "cust-31",
    name: "Karan Bhasin",
    email: "karan.b@paytm.com",
    clientType: "Corporate Professional",
    origin: "Noida",
    destination: "Jaipur",
    durationDays: 2,
    travelers: 1,
    plannedBudget: 15000,
    actualSpend: 13900,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.6,
    clientCollaborationNote: "Vande Bharat Delhi-Jaipur booking suggestion reduced journey from 6 hours road drive to 3.5 hrs train.",
    joinedDate: "2026-09-21",
  },
  {
    id: "cust-32",
    name: "Sunita & Ashish Roy",
    email: "sunita.roy@iitkgp.ac.in",
    clientType: "Weekend Couple",
    origin: "Kolkata",
    destination: "Digha",
    durationDays: 2,
    travelers: 2,
    plannedBudget: 12000,
    actualSpend: 11400,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 4.8,
    clientCollaborationNote: "Seafood dinner price estimates at Old Digha beach shacks were exact to current market menu.",
    joinedDate: "2026-09-21",
  },
  {
    id: "cust-33",
    name: "Naveen Rajan (Civil Batch)",
    email: "naveen.civil@psgtech.ac.in",
    clientType: "Student Group",
    origin: "Coimbatore",
    destination: "Kodaikanal",
    durationDays: 3,
    travelers: 6,
    plannedBudget: 26000,
    actualSpend: 24700,
    conversionStage: "Expense Tracking Active",
    feedbackRating: 4.7,
    clientCollaborationNote: "Group minibus rental split calculations verified by all 6 members via app dashboard.",
    joinedDate: "2026-09-22",
  },
  {
    id: "cust-34",
    name: "Aparna Murthy",
    email: "aparna.m@stjohns.in",
    clientType: "Solo Backpacker",
    origin: "Bangalore",
    destination: "Shimoga (Jog Falls)",
    durationDays: 2,
    travelers: 1,
    plannedBudget: 8500,
    actualSpend: 7900,
    conversionStage: "Trip Planned",
    feedbackRating: 4.8,
    clientCollaborationNote: "KSRTC Rajahamsa bus timing and entry viewpoint staircase fees budgeted properly.",
    joinedDate: "2026-09-22",
  },
  {
    id: "cust-35",
    name: "Venkatesh & Sangeetha",
    email: "venkatesh.s@hcl.com",
    clientType: "Family Vacationer",
    origin: "Bangalore",
    destination: "Mysore & Bandipur",
    durationDays: 3,
    travelers: 4,
    plannedBudget: 34000,
    actualSpend: 32600,
    conversionStage: "Payment Completed (Premium)",
    feedbackRating: 5.0,
    clientCollaborationNote: "Bandipur tiger reserve safari booking and Mysore Palace evening illumination timings and parking fees accurately integrated.",
    joinedDate: "2026-09-23",
  },
];

export function getCustomerCohortSummary() {
  const totalCustomers = EVALUATION_CUSTOMERS.length;
  const totalPlanned = EVALUATION_CUSTOMERS.reduce((sum, c) => sum + c.plannedBudget, 0);
  const totalActual = EVALUATION_CUSTOMERS.reduce((sum, c) => sum + c.actualSpend, 0);
  const totalSavings = totalPlanned - totalActual;
  const avgSatisfaction = (
    EVALUATION_CUSTOMERS.reduce((sum, c) => sum + c.feedbackRating, 0) / totalCustomers
  ).toFixed(2);

  const clientTypeCounts: Record<string, number> = {};
  const stageCounts: Record<string, number> = {};

  EVALUATION_CUSTOMERS.forEach((c) => {
    clientTypeCounts[c.clientType] = (clientTypeCounts[c.clientType] || 0) + 1;
    stageCounts[c.conversionStage] = (stageCounts[c.conversionStage] || 0) + 1;
  });

  return {
    totalCustomers,
    totalPlanned,
    totalActual,
    totalSavings,
    avgSatisfaction,
    clientTypeCounts,
    stageCounts,
  };
}
